// <auto-generated />
using LoginTokenTask.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginTokenTask.Migrations
{
    [DbContext(typeof(LoginDbContext))]
    partial class LoginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoginTokenTask.Models.Gadget", b =>
                {
                    b.Property<string>("GadgetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GadgetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GadgetPrice")
                        .HasColumnType("int");

                    b.Property<string>("GadgetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GadgetId");

                    b.ToTable("GagetTbl");
                });

            modelBuilder.Entity("LoginTokenTask.Models.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
